apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: front-app
          image: front-app/gitops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
