apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: mohamedamine1/frontend-azure:frontend
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://my-nest-app-service:3001"
