apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 # Port spécifique sur lequel le service sera exposé sur chaque nœud
