apiVersion: v1
kind: Service
metadata:
  name: { { include "mon-application.fullname" . } }
  labels:
    app: { { include "mon-application.name" . } }
spec:
  selector:
    app: { { include "mon-application.name" . } }
  ports:
    - protocol: TCP
      port: 80 # Le port sur lequel votre application écoute à l'intérieur du conteneur
      targetPort: 80 # Le port sur lequel votre application écoute à l'intérieur du conteneur
  type: LoadBalancer # Type de service, assurez-vous que cela convient à votre environnement (ClusterIP, NodePort, LoadBalancer, etc.)
