apiVersion: argoproj.io/v1alpha1
kind: HelmRelease
metadata:
  name: react-app
spec:
  chart:
    repository: https://charts.example.com/stable
    name: my-react-app
    version: 1.0.0
  values:
    replicaCount: 3
    image:
      repository: mohamedamine1/frontend
      tag: frontend-pfe
      pullPolicy: IfNotPresent
    service:
      name: my-react-app-service
      type: LoadBalancer
      port: 80
