apiVersion: apps/v1
kind: HelmRelease
metadata:
  name: my-react-app
spec:
  chart:
    # Assuming your React application is packaged as a Helm chart and available in this repository
    repository: https://charts.example.com/stable
    name: my-react-app
    version: 1.0.0 # Adjust the version as per your chart
  values:
    replicaCount: 1
    image:
      repository: mohamedamine1/frontend
      tag: frontend-pfe
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      port: 80
    containerPort: 3000
